name: rotary_scrollbar
description: circular scrollbar for Wear OS devices. It can be controlled with rotary input and it includes haptic feedback.
version: 0.1.1
homepage: https://github.com/hyperfluid-tech/rotary_scrollbar

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  wearable_rotary: ^2.0.0
  vibration: ^1.7.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
